-- CALENDAR EVENTS TABLE
CREATE TABLE IF NOT EXISTS public.calendar_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    end_time TIMESTAMP WITH TIME ZONE,
    event_type TEXT DEFAULT 'event', -- 'event', 'holiday', 'class', 'deadline'
    created_by UUID REFERENCES auth.users(id)
);

-- RLS
ALTER TABLE public.calendar_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to events"
ON public.calendar_events FOR SELECT
USING (true);

CREATE POLICY "Allow admin to manage events"
ON public.calendar_events FOR ALL
USING (
  exists (
    select 1 from public.profiles
    where profiles.uid = auth.uid() and profiles.role = 'admin'
  )
);
