-- 1. NOTICES TABLE (For Announcements)
CREATE TABLE IF NOT EXISTS public.notices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    title TEXT NOT NULL,
    content TEXT,
    priority TEXT DEFAULT 'normal', -- 'normal', 'urgent'
    is_active BOOLEAN DEFAULT TRUE,
    created_by UUID REFERENCES auth.users(id)
);

-- RLS for Notices
ALTER TABLE public.notices ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to active notices"
ON public.notices FOR SELECT
USING (true);

CREATE POLICY "Allow admin to insert/update notices"
ON public.notices FOR ALL
USING (
  exists (
    select 1 from public.profiles
    where profiles.uid = auth.uid() and profiles.role = 'admin'
  )
);

-- 2. USER ACHIEVEMENTS TABLE
CREATE TABLE IF NOT EXISTS public.user_achievements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    badge_key TEXT NOT NULL, -- e.g., 'speed_coder', 'first_login'
    awarded_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    UNIQUE(user_id, badge_key)
);

-- RLS for Achievements
ALTER TABLE public.user_achievements ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own achievements"
ON public.user_achievements FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "System/Admin can award achievements"
ON public.user_achievements FOR INSERT
WITH CHECK (true); -- Ideally restricted, but for this app openness is okay, or triggered by edge functions. 
-- For simplicity in this client-side app, we'll allow authenticated users to insert (self-award logic verified by client) 
-- OR strictly restrict to admin/procedures. 
-- Let's stick to: Users can insert their own for now (trusting client logic for this prototype) to avoid complex backend triggers.
CREATE POLICY "Users can insert own achievements" 
ON public.user_achievements FOR INSERT 
WITH CHECK (auth.uid() = user_id);

-- 3. CHAT MESSAGES (Enhancement to existing or new)
CREATE TABLE IF NOT EXISTS public.chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    sender_id UUID REFERENCES auth.users(id) NOT NULL,
    recipient_id UUID REFERENCES auth.users(id), -- Null means public/group chat if we wanted, but we want 1-on-1 with admin
    message TEXT NOT NULL,
    is_read BOOLEAN DEFAULT FALSE
);

-- RLS for Chat
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read messages sent to them or by them"
ON public.chat_messages FOR SELECT
USING (auth.uid() = sender_id OR auth.uid() = recipient_id);

CREATE POLICY "Users can send messages"
ON public.chat_messages FOR INSERT
WITH CHECK (auth.uid() = sender_id);

CREATE POLICY "Users can update read status of received messages"
ON public.chat_messages FOR UPDATE
USING (auth.uid() = recipient_id);
