-- Safe and Robust Setup for direct_messages
-- This script replaces or updates the schema without losing data.

-- 1. Create Table (if not exists)
CREATE TABLE IF NOT EXISTS public.direct_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id UUID REFERENCES auth.users(id) NOT NULL,
    receiver_id UUID REFERENCES auth.users(id) NOT NULL,
    content TEXT NOT NULL,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Ensure Columns Exist (Idempotent updates)
DO $$
BEGIN
    -- We use a block to safely add columns if they were missing from an old version
    BEGIN
        ALTER TABLE public.direct_messages ADD COLUMN IF NOT EXISTS sender_id UUID REFERENCES auth.users(id) NOT NULL;
    EXCEPTION WHEN duplicate_object THEN NULL; END;
    
    BEGIN
        ALTER TABLE public.direct_messages ADD COLUMN IF NOT EXISTS receiver_id UUID REFERENCES auth.users(id) NOT NULL;
    EXCEPTION WHEN duplicate_object THEN NULL; END;

    BEGIN
        ALTER TABLE public.direct_messages ADD COLUMN IF NOT EXISTS content TEXT NOT NULL;
    EXCEPTION WHEN duplicate_object THEN NULL; END;

    BEGIN
        ALTER TABLE public.direct_messages ADD COLUMN IF NOT EXISTS is_read BOOLEAN DEFAULT FALSE;
    EXCEPTION WHEN duplicate_object THEN NULL; END;
END $$;

-- 3. Enable Row Level Security (Always safe to run)
ALTER TABLE public.direct_messages ENABLE ROW LEVEL SECURITY;

-- 4. Refresh Policies (DROP and RECREATE to update logic)
DROP POLICY IF EXISTS "Users can view their own messages" ON public.direct_messages;
CREATE POLICY "Users can view their own messages"
ON public.direct_messages FOR SELECT
USING (auth.uid() = sender_id OR auth.uid() = receiver_id);

DROP POLICY IF EXISTS "Users can insert messages" ON public.direct_messages;
CREATE POLICY "Users can insert messages"
ON public.direct_messages FOR INSERT
WITH CHECK (auth.uid() = sender_id);

DROP POLICY IF EXISTS "Users can update read status of received messages" ON public.direct_messages;
CREATE POLICY "Users can update read status of received messages"
ON public.direct_messages FOR UPDATE
USING (auth.uid() = receiver_id);

-- 5. Enable Realtime (Idempotent check)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'direct_messages') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.direct_messages;
  END IF;
END $$;
