-- Setup Announcements Table (Fixed Permissions)
-- This table allows admins to broadcast messages to all students.

CREATE TABLE IF NOT EXISTS public.announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    priority TEXT DEFAULT 'normal', -- 'normal', 'urgent', 'info'
    created_by UUID REFERENCES auth.users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;

-- Policies
-- 1. Everyone can read announcements
DROP POLICY IF EXISTS "Public read access" ON public.announcements;
CREATE POLICY "Public read access" ON public.announcements FOR SELECT USING (true);

-- 2. Admins (created_by) can insert
DROP POLICY IF EXISTS "Admins can insert" ON public.announcements;
CREATE POLICY "Admins can insert" ON public.announcements FOR INSERT WITH CHECK (auth.uid() = created_by);

-- 3. Admins (created_by) can delete (CRITICAL FIX)
DROP POLICY IF EXISTS "Admins can delete" ON public.announcements;
CREATE POLICY "Admins can delete" ON public.announcements FOR DELETE USING (auth.uid() = created_by);

-- Enable Realtime
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'announcements') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.announcements;
  END IF;
END $$;
