-- ROBUST SETUP SCRIPT (Safe to run multiple times)

-- 1. ARCADE CONFIG (Global Lock)
CREATE TABLE IF NOT EXISTS public.arcade_config (
    id bigint generated by default as identity primary key,
    is_unlocked boolean default false,
    updated_at timestamp with time zone default timezone('utc'::text, now())
);

ALTER TABLE public.arcade_config ENABLE ROW LEVEL SECURITY;

-- 2. USER PROGRESS (Strength Levels)
CREATE TABLE IF NOT EXISTS public.user_arcade_progress (
    user_id uuid references auth.users not null primary key,
    html_level text default 'easy',
    css_level text default 'easy',
    updated_at timestamp with time zone default timezone('utc'::text, now())
);

ALTER TABLE public.user_arcade_progress ENABLE ROW LEVEL SECURITY;


-- 3. POLICIES (Drop existing first to avoid errors, then recreate)

-- Policies for arcade_config
DROP POLICY IF EXISTS "Read access for all" ON public.arcade_config;
CREATE POLICY "Read access for all" ON public.arcade_config FOR SELECT USING (true);

DROP POLICY IF EXISTS "Update access for auth users" ON public.arcade_config;
CREATE POLICY "Update access for auth users" ON public.arcade_config FOR UPDATE USING (auth.role() = 'authenticated');

-- Policies for user_arcade_progress
DROP POLICY IF EXISTS "Users can read own progress" ON public.user_arcade_progress;
CREATE POLICY "Users can read own progress" ON public.user_arcade_progress FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own progress" ON public.user_arcade_progress;
CREATE POLICY "Users can update own progress" ON public.user_arcade_progress FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own progress update" ON public.user_arcade_progress;
CREATE POLICY "Users can update own progress update" ON public.user_arcade_progress FOR UPDATE USING (auth.uid() = user_id);


-- 4. INITIAL DATA
INSERT INTO public.arcade_config (id, is_unlocked) VALUES (1, false) ON CONFLICT (id) DO NOTHING;

-- 5. REALTIME (Safe wrapper)
DO $$
BEGIN
    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE arcade_config;
    EXCEPTION WHEN OTHERS THEN
        NULL; -- Ignore if already added or publication missing
    END;
END
$$;
