-- Create Feedback Table
create table public.feedback (
  id bigint generated by default as identity primary key,
  student_id uuid references auth.users(id),
  student_name text,
  rating int,
  content_quality text,
  usability text,
  comments text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.feedback enable row level security;

-- Policy: Allow any authenticated user (student) to insert feedback
create policy "Enable insert for authenticated users only"
on public.feedback for insert
to authenticated
with check (true);

-- Policy: Allow admins (or everyone for now if RLS is simple) to read feedback
-- Assuming we want admins to see all feedback. 
-- For simplicity in this demo environment, we might allow public read or restricted read.
-- Let's allow public read for now so the admin dashboard (which might be client-side restricted) can fetch it.
create policy "Enable read access for all users"
on public.feedback for select
using (true);
